- hosts: primary
  vars_files:
    - vars.yaml
  vars:
    work_dir: "{{ zuul.project.src_dir }}/{{ zuul_osh_infra_relative_path | default('') }}"
  gather_facts: True
  roles:
    - k8s-create-image-secret
  tags:
    - k8s-create-image-secret
